# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: suite
    displayName: Suite
    type: string
    default: regression
    values:
      - regression
  - name: environment
    displayName: Environment
    type: string
    default: qa
    values:
      - qa

steps:
- task: Gradle@2
  displayName: Execute test
  condition: always()
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean ${{parameters.suite}} -Denvironment=${{parameters.environment}}'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

